routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'LandingController@index');

Route::get('/home', function() {
    return redirect(route('admin.home'));
});

Auth::routes(['register' => false]);

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::name('admin.')->group(function () {
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('category', 'CategoryController', ['except' => ['create', 'show']]);
        
        // Article
        Route::resource('article', 'PostController', ['except' => ['show']]);
        Route::get('article/trash', 'PostController@trashed')->name('article.trashed');
        Route::get('article/published', 'PostController@published')->name('article.published');
        Route::get('article/draft', 'PostController@draft')->name('article.draft');
        Route::post('article/{id}/trash', 'PostController@trash')->name('article.trash');
        Route::post('article/{id}/restore', 'PostController@restore')->name('article.restore');

        // Settings
        Route::get('settings', 'SettingController@index')->name('settings.index');
        Route::put('settings', 'SettingController@update')->name('settings.update');
    });
});

Route::group(['middleware' => 'auth'], function() {
    Route::get('account', 'UserController@index')->name('account.index');
    Route::put('account', 'UserController@profileUpdate')->name('account.edit-profile');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Post;

class Category extends Model
{
    protected $guarded = [];

    public static function getCategories()
    {
        $query = self::orderBy('title', 'ASC')->get();

        return $query;
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request, Illuminate\Support\Facades\DB, Illuminate\Support\Str;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $models = Category::getCategories();
            return DataTables::of($models)
                ->addColumn('title', function ($models) {
                    $links = "<a href=" . route('admin.category.edit', $models->id) . ">$models->title</a>";

                    return $links;
                })
                ->addColumn('action', function ($models) {
                    $button = "<a href=" . route('admin.category.edit', $models->id) . " class='btn btn-outline-primary btn-sm'>Edit</a>";
                    if ($models->id != 1) {
                        $button .= "&nbsp;&nbsp;";
                        $button .= "<form action=" . route('admin.category.destroy', $models->id) . " method='post' class='d-inline'>" . csrf_field() . method_field('delete') . "<button  class='btn btn-danger btn-sm text-white' type='submit'>Delete</button></form>";
                    }

                    return $button;
                })
                ->rawColumns(['title', 'action'])
                ->make(true);
        }

        return view('category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        DB::beginTransaction();

        try {
            Category::create([
                'title' => $request->title,
                'slug'  => Str::lower(str_replace(' ', '-', $request->title)),
                'image' => $request->image
            ]);

            DB::commit();
            return redirect(route('admin.category.index'))->with('success', 'Thank You for your subscription');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect(route('admin.category.index'))->with('warning', 'Something Went Wrong!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        DB::beginTransaction();

        try {
            Category::findOrFail($id)
                ->update([
                    'title' => $request->title,
                    'slug'  => Str::lower(str_replace(' ', '-', $request->title)),
                    'image' => $request->image
                ]);

            DB::commit();
            return redirect(route('admin.category.index'))->with('success', 'Thank You for your subscription');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect(route('admin.category.index'))->with('warning', 'Something Went Wrong!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::destroy($id);

        return redirect(route('admin.category.index'))->with('success', 'Thank You for your subscription');
    }
}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::getCategories();

        return response()->json([
            'status'    => true,
            'data'      => $categories
        ], 200);
    }

    public function show($id)
    {
        $categories = Category::findOrFail($id);
        $posts = Post::where('categories_id', $id)->latest()->paginate(10);

        return response()->json([
            'status'        => true,
            'data'          => [
                'category' => $categories,
                'posts'      => $posts
            ]
        ], 200);
    }
}

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('title', 'Ubah Kategori')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow mb-4">
                    <div class="card-body px-4">
                        <form action="{{ route('admin.category.update', $category->id) }}" method="post">
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                                <label for="title" class="col-form-label">Judul</label>
                                <input type="text" name="title" id="title"
                                    class="form-control @error('title') is-invalid @enderror"
                                    value="{{ $category->title }}">

                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="slug" class="col-form-label">Slug</label>
                                <input type="text" name="slug" id="slug" class="form-control"
                                    value="{{ $category->slug }}" readonly>
                            </div>
                            <div class="form-group">
                                <label for="image" class="col-form-label">Image</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="image" name="image"
                                        value="{{ $category->image }}">
                                    <div class="input-group-append">
                                        <span class="input-group-text"
                                            onclick="filemanager.selectFile('image')">Pilih</span>
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-sm btn-outline-primary float-right fe fe-send fe-16"> Submit</button>
                        </form>
                    </div> <!-- .card-body -->
                </div> <!-- .card -->
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function () {
        $('#title').keyup(function () {
            $('#slug').val($(this).val().replace(/ /g, '-'));
        });
    });

</script>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('title', 'Kategori')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="card shadow mb-4">
                    <div class="card-header">
                        <strong class="card-title">Tambah baru</strong>
                    </div>
                    <div class="card-body px-4">
                        <form action="{{ route('admin.category.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="title">Judul</label>
                                <input type="text" name="title" id="title"
                                    class="form-control @error('title') is-invalid @enderror">

                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" id="image" name="image" value="{{ old('image') }}">
                                    <div class="input-group-append">
                                        <span class="input-group-text" onclick="filemanager.selectFile('image')">Pilih</span>
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-sm btn-outline-primary float-right fe fe-send fe-16"> Submit</button>
                        </form>
                    </div> <!-- .card-body -->
                </div> <!-- .card -->
            </div>
            <div class="col-md-8">
                <div class="card shadow mb-4">
                    <div class="card-body px-4">
                        <div class="table-responsive">
                            <table id="table" class="table table-striped table-borderless mb-1 mx-n1 table-sm">
                                <thead>
                                    <tr>
                                        <th>Judul</th>
                                        <th>Slug</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div> <!-- .card-body -->
                </div> <!-- .card -->
            </div> <!-- .col -->
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function () {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.category.index') }}"
            },
            responsive: true,
            "columns": [{
                    data: 'title',
                    name: 'title'
                },
                {
                    data: 'slug',
                    name: 'slug',
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })
    })

</script>
@endsection