routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'LandingController@index');

Route::get('/home', function() {
    return redirect(route('admin.home'));
});

Auth::routes(['register' => false]);

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::name('admin.')->group(function () {
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('category', 'CategoryController', ['except' => ['create', 'show']]);
        
        // Article
        Route::resource('article', 'PostController', ['except' => ['show']]);
        Route::get('article/trash', 'PostController@trashed')->name('article.trashed');
        Route::get('article/published', 'PostController@published')->name('article.published');
        Route::get('article/draft', 'PostController@draft')->name('article.draft');
        Route::post('article/{id}/trash', 'PostController@trash')->name('article.trash');
        Route::post('article/{id}/restore', 'PostController@restore')->name('article.restore');

        // Settings
        Route::get('settings', 'SettingController@index')->name('settings.index');
        Route::put('settings', 'SettingController@update')->name('settings.update');
    });
});

Route::group(['middleware' => 'auth'], function() {
    Route::get('account', 'UserController@index')->name('account.index');
    Route::put('account', 'UserController@profileUpdate')->name('account.edit-profile');
});

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Artikel Baru')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
            </div>
        </div>
        <form action="{{ route('admin.article.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title') }}" placeholder="Tambahkan judul" autofocus>
                        
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <textarea name="editor" id="editor" class="form-control editor @error('editor') is-invalid @enderror">{{ old('editor') }}</textarea>
                    
                        @error('editor')
                        <span class="invalid-feedback" role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div> <!-- .col -->
                <div class="col-md-4">
                    <div class="card mt-2">
                        <div class="card-header">Thumbnail Image</div>
                        <div class="card-body">
                            <input type="hidden" id="thumb" name="thumb" value="{{ old('thumb') }}">
                            <img src="{{ old('thumb') }}" id="thumb-preview" style="width: 100%;">
                        </div>
                        <div class="card-footer">
                            <button type="button" class="btn btn-sm btn-outline-primary" onclick="filemanager.selectFile('thumb')">Set featured image</button>
                            <button type="button" class="btn btn-sm btn-outline-danger float-right" onclick="remove();"> Remove featured image</button>
                        </div>
                    </div>
                    <div class="card mt-2">
                        <div class="card-header">Kategori</div>
                        <div class="card-body">
                            <div class="form-group" style="margin: 0;">
                                <select name="category" id="category" class="form-control select2 @error('category') is-invalid @enderror">
                                    <option value="">Select</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}" @if($category->id == old('category')) selected @endif>{{ $category->title }}</option>
                                    @endforeach
                                </select>

                                @error('category')
                                <span class="invalid-feedback" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="card mt-2">
                        <div class="card-header">Publish</div>
                        <div class="card-body">
                            <p style="margin: 0;"><span class="fe fe-key fe-16"></span> Status : <strong>Unknown</strong></p>
                        </div>
                        <div class="card-footer">
                            <button type="submit" name="publish" value="0" class="btn btn-sm btn-outline-danger fe fe-save fe-16"> Save Draft</button>
                            <button type="submit" name="publish" value="1" class="btn btn-sm btn-outline-primary float-right fe fe-send fe-16"> Publish</button>
                        </div>
                    </div>
                </div>
            </div> <!-- .row -->
        </form>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
	window.onload = function () {
        $('.select2').select2();
		CKEDITOR.replace('editor', {
	        filebrowserBrowseUrl: filemanager.ckBrowseUrl,
	    });
	}

    function remove() {
        let thumb = document.getElementById('thumb')
        let thumbPrev = document.getElementById('thumb-preview')

        thumb.value = ''
        thumbPrev.src = ''
    }
</script>
@endsection

resources/views/articles/draft.blade.php
@extends('layouts.app')

@section('title', 'Artikel Draft')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
                <a href="{{ route('admin.article.create') }}" class="btn btn-sm btn-outline-primary ml-auto"><span class="fe fe-plus fe-16 mr-2"></span>Tambah Baru</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header">
                        @if($data->trash)
                            <a class="float-right ml-2" href="{{ route('admin.article.trashed') }}">Trash ({{ $data->trash }})</a>
                        @endif
                        @if($data->published)
                            <a class="float-right ml-2" href="{{ route('admin.article.published') }}">Published ({{ $data->published }})</a>
                        @endif
                        @if($data->draft)
                            <a class="float-right ml-2" href="{{ route('admin.article.draft') }}">Draft ({{ $data->draft }})</a>
                        @endif
                        <a class="float-right" href="{{ route('admin.article.index') }}">All ({{ $data->all }})</a>
                    </div>
                    <div class="card-body px-4">
                        <div class="table-responsive">
                            <table id="table" class="table table-striped table-borderless mb-1 mx-n1 table-sm">
                                <thead>
                                    <tr>
                                        <th>Judul</th>
                                        <th>Author</th>
                                        <th>Kategori</th>
                                        <th>Tanggal</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div> <!-- .card-body -->
                </div> <!-- .card -->
            </div> <!-- .col -->
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.article.draft') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'title',
                    name: 'title'
                },
                {
                    data: 'user.name',
                    name: 'user.name',
                    orderable: false
                },
                {
                    data: 'categories.title',
                    name: 'categories.title',
                    orderable: false
                },
                {
                    data: 'date',
                    name: 'date',
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })
    })
</script>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('title', 'Ubah Artikel')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
            </div>
        </div>
        <form action="{{ route('admin.article.update', $article->id) }}" method="post">
            @method('PUT')
            @csrf
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ $article->title }}" placeholder="Ubah judul">
                        
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <textarea name="editor" id="editor" class="form-control editor @error('editor') is-invalid @enderror">{{ $article->article }}</textarea>
                    
                        @error('editor')
                        <span class="invalid-feedback" role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div> <!-- .col -->
                <div class="col-md-4">
                    <div class="card mt-2">
                        <div class="card-header">Thumbnail Image</div>
                        <div class="card-body">
                            <input type="hidden" id="thumb" name="thumb" value="{{ $article->thumb }}">
                            <img src="{{ $article->thumb }}" id="thumb-preview" style="width: 100%;">
                        </div>
                        <div class="card-footer">
                            <button type="button" class="btn btn-sm btn-outline-primary" onclick="filemanager.selectFile('thumb')">Set featured image</button>
                            <button type="button" class="btn btn-sm btn-outline-danger float-right" onclick="remove();"> Remove featured image</button>
                        </div>
                    </div>
                    <div class="card mt-2">
                        <div class="card-header">Kategori</div>
                        <div class="card-body">
                            <div class="form-group" style="margin: 0;">
                                <select name="category" id="category" class="form-control select2 @error('category') is-invalid @enderror">
                                    <option value="">Select</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}" @if($category->id == $article->categories_id) selected @endif>{{ $category->title }}</option>
                                    @endforeach
                                </select>

                                @error('category')
                                <span class="invalid-feedback" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="card mt-2">
                        <div class="card-header">Publish</div>
                        <div class="card-body">
                            <p style="margin: 0;"><span class="fe fe-key fe-16"></span> Status : <strong>@if($article->published == 0) Draft @else Published @endif</strong></p>
                        </div>
                        <div class="card-footer">
                            <button type="submit" name="publish" value="0" class="btn btn-sm btn-outline-danger fe fe-save fe-16"> Save Draft</button>
                            <button type="submit" name="publish" value="1" class="btn btn-sm btn-outline-primary float-right fe fe-send fe-16"> Publish</button>
                        </div>
                    </div>
                </div>
            </div> <!-- .row -->
        </form>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
	window.onload = function () {
        $('.select2').select2();
		CKEDITOR.replace('editor', {
	        filebrowserBrowseUrl: filemanager.ckBrowseUrl,
	    });
	}

    function remove() {
        let thumb = document.getElementById('thumb')
        let thumbPrev = document.getElementById('thumb-preview')

        thumb.value = ''
        thumbPrev.src = ''
    }
</script>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('title', 'Artikel')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
                <a href="{{ route('admin.article.create') }}" class="btn btn-sm btn-outline-primary ml-auto"><span class="fe fe-plus fe-16 mr-2"></span>Tambah Baru</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header">
                        @if($data->trash)
                            <a class="float-right ml-2" href="{{ route('admin.article.trashed') }}">Trash ({{ $data->trash }})</a>
                        @endif
                        @if($data->published)
                            <a class="float-right ml-2" href="{{ route('admin.article.published') }}">Published ({{ $data->published }})</a>
                        @endif
                        @if($data->draft)
                            <a class="float-right ml-2" href="{{ route('admin.article.draft') }}">Draft ({{ $data->draft }})</a>
                        @endif
                        <a class="float-right" href="{{ route('admin.article.index') }}">All ({{ $data->all }})</a>
                    </div>
                    <div class="card-body px-4">
                        <div class="table-responsive">
                            <table id="table" class="table table-striped table-borderless mb-1 mx-n1 table-sm">
                                <thead>
                                    <tr>
                                        <th>Judul</th>
                                        <th>Author</th>
                                        <th>Kategori</th>
                                        <th>Tanggal</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div> <!-- .card-body -->
                </div> <!-- .card -->
            </div> <!-- .col -->
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.article.index') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'title',
                    name: 'title'
                },
                {
                    data: 'user.name',
                    name: 'user.name',
                    orderable: false
                },
                {
                    data: 'categories.title',
                    name: 'categories.title',
                    orderable: false
                },
                {
                    data: 'date',
                    name: 'date',
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })
    })
</script>
@endsection

resources/views/articles/published.blade.php
@extends('layouts.app')

@section('title', 'Artikel Published')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
                <a href="{{ route('admin.article.create') }}" class="btn btn-sm btn-outline-primary ml-auto"><span class="fe fe-plus fe-16 mr-2"></span>Tambah Baru</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header">
                        @if($data->trash)
                            <a class="float-right ml-2" href="{{ route('admin.article.trashed') }}">Trash ({{ $data->trash }})</a>
                        @endif
                        @if($data->published)
                            <a class="float-right ml-2" href="{{ route('admin.article.published') }}">Published ({{ $data->published }})</a>
                        @endif
                        @if($data->draft)
                            <a class="float-right ml-2" href="{{ route('admin.article.draft') }}">Draft ({{ $data->draft }})</a>
                        @endif
                        <a class="float-right" href="{{ route('admin.article.index') }}">All ({{ $data->all }})</a>
                    </div>
                    <div class="card-body px-4">
                        <div class="table-responsive">
                            <table id="table" class="table table-striped table-borderless mb-1 mx-n1 table-sm">
                                <thead>
                                    <tr>
                                        <th>Judul</th>
                                        <th>Author</th>
                                        <th>Kategori</th>
                                        <th>Tanggal</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div> <!-- .card-body -->
                </div> <!-- .card -->
            </div> <!-- .col -->
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.article.published') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'title',
                    name: 'title'
                },
                {
                    data: 'user.name',
                    name: 'user.name',
                    orderable: false
                },
                {
                    data: 'categories.title',
                    name: 'categories.title',
                    orderable: false
                },
                {
                    data: 'date',
                    name: 'date',
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })
    })
</script>
@endsection

resources/views/articles/trashed.blade.php
@extends('layouts.app')

@section('title', 'Artikel')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
                <a href="{{ route('admin.article.create') }}" class="btn btn-sm btn-outline-primary ml-auto"><span class="fe fe-plus fe-16 mr-2"></span>Tambah Baru</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header">
                        @if($data->trash)
                            <a class="float-right ml-2" href="{{ route('admin.article.trashed') }}">Trash ({{ $data->trash }})</a>
                        @endif
                        @if($data->published)
                            <a class="float-right ml-2" href="{{ route('admin.article.published') }}">Published ({{ $data->published }})</a>
                        @endif
                        @if($data->draft)
                            <a class="float-right ml-2" href="{{ route('admin.article.draft') }}">Draft ({{ $data->draft }})</a>
                        @endif
                        <a class="float-right" href="{{ route('admin.article.index') }}">All ({{ $data->all }})</a>
                    </div>
                    <div class="card-body px-4">
                        <div class="table-responsive">
                            <table id="table" class="table table-striped table-borderless mb-1 mx-n1 table-sm">
                                <thead>
                                    <tr>
                                        <th>Judul</th>
                                        <th>Author</th>
                                        <th>Kategori</th>
                                        <th>Tanggal</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div> <!-- .card-body -->
                </div> <!-- .card -->
            </div> <!-- .col -->
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.article.trashed') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'title',
                    name: 'title'
                },
                {
                    data: 'user.name',
                    name: 'user.name',
                    orderable: false
                },
                {
                    data: 'categories.title',
                    name: 'categories.title',
                    orderable: false
                },
                {
                    data: 'date',
                    name: 'date',
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })
    })
</script>
@endsection