routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'LandingController@index');

Route::get('/home', function() {
    return redirect(route('admin.home'));
});

Auth::routes(['register' => false]);

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::name('admin.')->group(function () {
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('category', 'CategoryController', ['except' => ['create', 'show']]);
        
        // Article
        Route::resource('article', 'PostController', ['except' => ['show']]);
        Route::get('article/trash', 'PostController@trashed')->name('article.trashed');
        Route::get('article/published', 'PostController@published')->name('article.published');
        Route::get('article/draft', 'PostController@draft')->name('article.draft');
        Route::post('article/{id}/trash', 'PostController@trash')->name('article.trash');
        Route::post('article/{id}/restore', 'PostController@restore')->name('article.restore');

        // Settings
        Route::get('settings', 'SettingController@index')->name('settings.index');
        Route::put('settings', 'SettingController@update')->name('settings.update');
    });
});

Route::group(['middleware' => 'auth'], function() {
    Route::get('account', 'UserController@index')->name('account.index');
    Route::put('account', 'UserController@profileUpdate')->name('account.edit-profile');
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $hidden = ['created_at', 'updated_at'];

    public static function settings() {
        $setting = new self;
        $setting->title = self::title();
        $setting->description = self::description();
        $setting->favicon = self::favicon();
        $setting->appLink = self::appLink();

        return $setting;
    }

    public static function title() {
        $setting = self::where('variable', 'title')->first();
        
        return $setting->value;
    }

    public static function description() {
        $setting = self::where('variable', 'description')->first();
        
        return $setting->value;
    }

    public static function favicon() {
        $setting = self::where('variable', 'favicon')->first();
        
        return $setting->value;
    }
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request, Illuminate\Support\Facades\DB;;
use App\Http\Requests\SettingRequest;
use App\Models\Setting;

class SettingController extends Controller
{
    public function index() {
        $settings = Setting::get();

        return view('settings.index', compact('settings'));
    }

    public function update(SettingRequest $request) {
        DB::beginTransaction();

        try{
            $updates = $request->all();
            foreach($updates as $key => $value) {
                Setting::where('variable', $key)->update(['value' => $value]);
            }

            DB::commit();
            return redirect(route('admin.settings.index'))->with('success','Thank You for your subscription');
        } catch (\Exception $e){
            DB::rollback();
            return redirect(route('admin.settings.index'))->with('warning','Something Went Wrong!');
        }
    }
}

resources/views/settings/index.blade.php
@extends('layouts.app')

@section('title', 'Settings')

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row align-items-center mb-2">
            <div class="col">
                <h2 class="h5 page-title">@yield('title')</h2>
                <p class="text-muted">Pengaturan website</p>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card shadow mb-4">
                    <div class="card-header">
                        <strong class="card-title">@yield('title')</strong>
                    </div>
                    <div class="card-body px-4">
                        <form action="{{ route('admin.settings.update') }}" method="POST">
                            @method('PUT')
                            @csrf
                            <div class="row d-flex justify-content-center">
                                <div class="col-md-6">
                                    @foreach ($settings as $setting)
                                        @if ($setting->type == 'text')
                                            <div class="form-group">
                                                <label class="text-capitalize" for="{{ $setting->variable }}">{{ $setting->variable }}</label>
                                                <input type="text" name="{{ $setting->variable }}" id="{{ $setting->variable }}"
                                                class="form-control @error($setting->variable) is-invalid @enderror"
                                                value="{{ $setting->value }}">
                                                
                                                @error($setting->variable)
                                                <span class="invalid-feedback" role="alert">
                                                    <strong class="text-danger">{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        @else
                                            <div class="form-group">
                                                <label class="text-capitalize" for="{{ $setting->variable }}">{{ str_replace('-', ' ', $setting->variable) }}</label>
                                                <div class="input-group mb-3">
                                                    <input type="text" class="form-control @error($setting->variable) is-invalid @enderror" name="{{ $setting->variable }}" id="{{ $setting->variable }}" value="{{ $setting->value }}">
                                                    <div class="input-group-append">
                                                        <span class="input-group-text" id="{{ $setting->variable }}" onclick="filemanager.selectFile('{{ $setting->variable }}')" style="cursor: pointer">Pilih</span>
                                                    </div>
                                                    
                                                    @error($setting->variable)
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong class="text-danger">{{ $message }}</strong>
                                                    </span>
                                                    @enderror
                                                </div>
                                            </div>
                                        @endif
                                    @endforeach
                                    <button type="submit" class="btn btn-outline-primary float-right fe fe-send fe-16">
                                        Simpan Perubahan</button>
                                </div>
                            </div>
                        </form>
                    </div> <!-- .card-body -->
                </div> <!-- .card -->
            </div>
        </div>
    </div>
</div>
@endsection